# Joystick Inputs for Twist-Message (4 DOF)

axis:
  a1: axis_left_x
  a2: axis_left_y
  a3: axis_right_y
  a4: axis_l2
  a5: axis_r2

button:
  b1: button_dpad_up
  b2: button_dpad_down
  b3: button_dpad_left
  b4: button_dpad_right
  b5: button_cross
  b6: button_circle
  b7: button_square
  b8: button_triangle
  b9: button_trackpad
  b10: button_share
  
tello:
  inputs:
    linear:
      x: axis_left_y
      y: -axis_left_x
      z: axis_right_y
    angular:
      z: axis_r2 - axis_l2
  scales:
    linear:
      x: 100
      y: 100
      z: 100
    angular:
      z: 100
       
gazebo:
  inputs:
    linear:
      x: axis_left_y
      y: axis_left_x
      z: axis_right_y
    angular:
      z: axis_l2 - axis_r2
  scales:
    linear:
      x: 2
      y: 2
      z: 2
    angular:
      z: 2
       

inputs_tello:
  linear:
    x: axis_left_y
    y: -axis_left_x
    z: axis_right_y
  angular:
    z: axis_r2 - axis_l2
    
inputs_gazebo:
  linear:
    x: axis_left_y
    y: axis_left_x
    z: axis_right_y
  angular:
    z: axis_l2 - axis_r2
    
scales_tello:
  linear:
    x: 100
    y: 100
    z: 100
  angular:
    z: 100
    
scales_gazebo:
  linear:
    x: 2
    y: 2
    z: 3
  angular:
    z: 5
